let carArray = [

    novehicle = {
        'name' : 'NO VEHICLE',
        'price' : 0,
        'speed' : 1,
        'multivalue' : 1.00,
        'successrate' : 75,
        'image' : 'https://i.ibb.co/CK6yPpy/Motorcykel.png',
        'bought' : true,
        'equipped' : false,
    }, 
    bike = {
        'name' : 'City Bike',
        'price' : 500,
        'speed' : 0.900,
        'multivalue' : 1.05,
        'successrate' : 80,
        'image' : 'https://i.ibb.co/0C2tzH3/pixil-frame-0-1-Kopi.png',
        'bought' : false,
        'equipped' : false,
    }, 
    civil = {
        'name' : 'Civil Car',
        'price' : 1200,
        'speed' : 0.775,
        'multivalue' : 1.10,
        'successrate' : 85,
        'image' : 'https://i.ibb.co/51g1R4Q/pixil-frame-0-1.png',
        'bought' : true,
        'equipped' : true,
    }, 
    motorbike = {
        'name' : '60T - Motorbike',
        'price' : 2400,
        'speed' : 0.550,
        'multivalue' : 1.15,
        'successrate' : 90,
        'image' : 'https://i.ibb.co/CK6yPpy/Motorcykel.png',
        'bought' : false,
        'equipped' : false,
    }, 
    pickup = {
        'name' : 'Pick-Up Truck',
        'price' : 3000,
        'speed' : 0.675,
        'multivalue' : 1.20,
        'successrate' : 95,
        'image' : 'https://i.ibb.co/CMKbjSs/Pick-up-truck.png',
        'bought' : false,
        'equipped' : false,
    },
    
    ]