let drugArray = [

    heroin = {
        'name' : 'Heroin',
        'buyinventory' : 5,
        'sellinventory' : 5,
        'buyprice' : 25,
        'sellprice' : 50,
        'prodtime' : 75000,
        'image' : 'https://i.ibb.co/B6Mxh4q/Kanyle.png',
        'x' : 0,
        'y' : 0,
    }, 
    weed = {
        'name' : 'Weed',
        'buyinventory' : 5,
        'sellinventory' : 5,
        'buyprice' : 15,
        'sellprice' : 30,
        'prodtime' : 45000,
        'image' : 'https://i.ibb.co/BfKddzg/weed.png',
        'x' : 0,
        'y' : 0,
    }, 
    coke = {
        'name' : 'Coke',
        'buyinventory' : 5,
        'sellinventory' : 5,
        'buyprice' : 45,
        'sellprice' : 90,
        'prodtime' : 135000,
        'image' : 'https://i.ibb.co/Xk7dkr5/Coke-bag.png',
        'x' : 0,
        'y' : 0,
    }, 
    mdma = {
        'name' : 'MDMA',
        'buyinventory' : 5,
        'sellinventory' : 5,
        'buyprice' : 30,
        'sellprice' : 60,
        'prodtime' : 90000,
        'image' : 'https://i.ibb.co/RP2cmSz/molly.png',
        'x' : 0,
        'y' : 0,
    },
    
    ]